env:
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: true
  no-underscore-dangle:
    - error
    - allow: [_id]
      allowAfterThis: true
      allowAfterSuper: true
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-use-before-define:
    - error
    - functions: false
  no-param-reassign:
    - error
    - props: false
  import/prefer-default-export: off
  max-classes-per-file: off
  class-methods-use-this: off
